---
name: Static Analysis

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/static-analysis.yaml'
      - 'vendor/**'
      - 'internal/**.go'

concurrency:
  group: 'staticAnalysys-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  detect:
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-static-analysis.sh